# Generated by Django 4.0.6 on 2022-07-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passwrd',
            new_name='password',
        ),
    ]
