# Generated by Django 4.0.6 on 2022-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='local',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
