# Generated by Django 4.0.6 on 2022-07-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Scheduler',
        ),
    ]
