# Generated by Django 4.0.6 on 2022-07-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_rename_schedule_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='day',
            field=models.DateField(),
        ),
    ]
